config/routes.rb
Rails.application.routes.draw do
  root "customers#index"
  resources :customers do
    resources :highlight_types do
      patch :move, on: :member
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :highlight_types, -> { order(:position) }, dependent: :destroy

  def highlight_types_fingerprint
    highlight_types_values = highlight_types.map { |ht| [ht.id, ht.name, ht.position] }
    Digest::MD5.hexdigest(highlight_types_values.to_s)
  end
end

app/models/highlight.rb
class Highlight < ApplicationRecord
  belongs_to :customer
  acts_as_list scope: :customer, add_new_at: :top, top_of_list: 0
  validates :name, presence: true, uniqueness: { scope: :customer_id }
  validates :color, inclusion: { in: %w[#red #blue #green #yellow #white #orange #purple #pink] }
end

app/models/highlight_type.rb
class HighlightType < ApplicationRecord
  belongs_to :customer
  acts_as_list scope: :customer, top_of_list: 0, add_new_at: :top
  validates :name, presence: true, uniqueness: {scope: :customer_id}
  validates :color, inclusion: {in: %w[#red #blue #green #yellow #white #orange #purple #pink]}

  def move(new_position, highlight_types_fingerprint)
    customer.with_lock do
      expected_fingerprint = customer.reload.highlight_types_fingerprint
      if highlight_types_fingerprint != expected_fingerprint
        errors.add(:highlight_types_fingerprint, "value #{highlight_types_fingerprint} does not match expected value #{expected_fingerprint}")
        return false
      end
      update!(position: new_position) # acts_as_list should never fail to handle this update
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # skip_before_action :verify_authenticity_token, if: :skip_verify_authenticity_token?
  # def skip_verify_authenticity_token?
  #   Rails.env.development? && params[:skip_verify_authenticity_token].present?
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[show edit update destroy]

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to edit_customer_path(@customer), notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to edit_customer_path(@customer), notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_customer
    @customer = Customer.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def customer_params
    params.require(:customer).permit(:name)
  end
end

app/controllers/highlight_types_controller.rb
class HighlightTypesController < ApplicationController
  before_action :set_customer
  before_action :set_highlight_type, except: [:index, :new, :create]

  def index
    @highlight_types = @customer.highlight_types
  end

  def show
  end

  def new
    @highlight_type = @customer.highlight_types.new
  end

  def edit
  end

  def create
    @highlight_type = @customer.highlight_types.new(highlight_params) # new items will be placed at beginning of list
    respond_to do |format|
      if @highlight_type.save
        format.html { redirect_to edit_customer_path(@customer), notice: "Highlight type was successfully created." }
        format.json { render :show, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity, notice: "Highlight type creation failed." }
        format.json { render json: @highlight_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @highlight_type.update(highlight_params)
        format.html { redirect_to edit_customer_path(@customer), notice: "Highlight type was successfully updated." }
        format.json { render :show, status: :ok }
      else
        format.html { render :edit, status: :unprocessable_entity, notice: "Highlight type update failed." }
        format.json { render json: @highlight_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def move
    respond_to do |format|
      format.html { redirect_to edit_customer_path(@customer), notice: "This action does not support html format" }
      format.json do
        if @highlight_type.move(move_params[:position], move_params[:highlight_types_fingerprint])
          render :show, status: :ok
        else
          flash.keep[:notice] = "Your change could not be applied because another user has modified the list. Please try again."
          render json: @highlight_type.errors, status: :conflict
        end
      end
    end
  end

  def destroy
    @highlight_type.destroy
    respond_to do |format|
      format.html { redirect_to edit_customer_path(@customer), notice: "Highlight type was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private

  def set_customer
    @customer = Customer.find(params.require(:customer_id))
  end

  def set_highlight_type
    @highlight_type = @customer.highlight_types.find(params.require(:id))
  end

  def highlight_params
    params.require(:highlight_type).permit(:name, :color)
  end

  def move_params
    params.require(:highlight_type).permit(:position, :highlight_types_fingerprint)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/highlight_types_helper.rb
module HighlightTypesHelper
end

app/views/customers/_customer.html.erb
<div id="<%= dom_id customer %>">
  <p>
    <strong>Name:</strong>
    <%= customer.name %>
  </p>

</div>

app/views/customers/_form.html.erb
<div class="border-2 border-gray-200">
  <%= form_with(model: customer, class: "border border-gray-300") do |form| %>
    <% if customer.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>
        <ul>
          <% customer.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="md:flex md:items-center mb-6 pt-6">
      <div class="md:w-1/3">
        <%= form.label 'Name:', class: "block md:text-right mb-1 md:mb-0 pr-4" %>
      </div>
      <div class="md:w-1/3">
        <%= form.text_field :name, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-blue-600" %>
      </div>
    </div>
    <div class="md:flex md:items-center pb-6">
      <div class="md:w-1/3"></div>
      <div class="md:w-1/3">
        <%= form.submit customer.persisted? ? "Update Customer Name" : "Create Customer", class: "bg-blue-600 px-3 py-3 text-base text-white rounded-md hover:bg-blue-700 hover:border-blue-700 border-transparent border-solid cursor-pointer" %>
      </div>
    </div>
  <% end %>
</div>

app/views/customers/edit.html.erb
<div class="text-md text-left mb-6"><%= link_to "Home", root_path, class: "text-blue-600 hover:underline" %> &#187; <%= link_to "Customers", customers_path, class: "text-blue-600 hover:underline" %> &#187; <%= @customer.name %> </div>
<div class="text-2xl text-left mb-6">Customer Profile</div>
<%= render "form", customer: @customer %>
<div class="border-1 md:mx-8">
  <div class="columns-2 flex items-center justify-between py-4">
    <div class="">
      <h4 class="text-2xl">Highlight Types</h4>
    </div>
    <div class="text-right border">
      <%= link_to new_customer_highlight_type_path(@customer), class: 'bg-green-600 px-3 py-3 text-base text-white rounded-md hover:bg-green-700 hover:border-green-700 border-transparent border-solid cursor-pointer inline-block' do %>
        Add New Highlight Type
      <% end %>
    </div>
  </div>
  <div data-controller="drag" data-drag-url="/customers/<%= @customer.id %>/highlight_types/:id/move.json", class="py-4">
    <% @customer.highlight_types.order(:position).each do |highlight_type| %>
      <div data-id="<%= highlight_type.id %>" data-highlight_types_fingerprint="<%= @customer.highlight_types_fingerprint %>" class="card card-body mb-4 border-b">
        <i class="fas fa-arrows-alt drag-handle"></i>&nbsp;&nbsp;
        <%= link_to highlight_type.name, edit_customer_highlight_type_path(@customer, highlight_type), class: "text-blue-600 hover:underline" %>
      </div>
    <% end %>
  </div>
</div>
<div>
  <%= link_to 'Delete Customer', customer_path(@customer), data: { "turbo-method": :delete }, class: "bg-red-600 px-3 py-3 text-base text-white rounded-md hover:bg-red-700 hover:border-red-700 border-transparent border-solid cursor-pointer inline-block" %>
</div>

app/views/customers/index.html.erb
<div class="text-md text-left mb-6"><%= link_to "Home", root_path, class: "text-blue-600 hover:underline" %> &#187; Customer </div>
<div class="border-1 md:mx-8">
  <div class="columns-2 flex items-center justify-between py-4">
    <div class="">
      <h4 class="text-2xl">Customers</h4>
    </div>
    <div class="text-right border">
      <%= link_to new_customer_path, class: 'bg-green-600 px-3 py-3 text-base text-white rounded-md hover:bg-green-700 hover:border-green-700 border-transparent border-solid cursor-pointer inline-block' do %>
        Add New Customer
      <% end %>
    </div>
  </div>
  <div class="py-4">
    <% @customers.order(:name).each do |customer| %>
      <div class="card card-body mb-4 border-b">
        <%= link_to customer.name, edit_customer_path(customer), class: "text-blue-600 hover:underline" %>
      </div>
    <% end %>
  </div>
</div>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Back to customers", customers_path %>
</div>

app/views/highlight_types/_form.html.erb
<div class="border-2 border-gray-200">
  <%= form_with(model: highlight_type, url: highlight_type.persisted? ? customer_highlight_type_path(@customer, highlight_type) : customer_highlight_types_path(@customer), class: "border border-gray-300") do |form| %>
    <% if highlight_type.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(highlight_type.errors.count, "error") %> prohibited this highlight_type from being saved:</h2>
        <ul>
          <% highlight_type.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="md:flex md:items-center mb-6 pt-6">
      <div class="md:w-1/3">
        <%= form.label 'Name', class: "block md:text-right mb-1 md:mb-0 pr-4" %>
      </div>
      <div class="md:w-1/3">
        <%= form.text_field :name, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-blue-600" %>
      </div>
    </div>
    <div class="md:flex md:items-center mb-6 pt-6">
      <div class="md:w-1/3">
        <%= form.label 'Color', class: "block md:text-right mb-1 md:mb-0 pr-4" %>
      </div>
      <div class="md:w-1/3">
        <%= form.text_field :color, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-blue-600" %>
      </div>
    </div>
    <div class="md:flex md:items-center pb-6">
      <div class="md:w-1/3"></div>
      <div class="md:w-1/3">
        <%= form.submit highlight_type.persisted? ? "Update Highlight Type" : "Create Highlight Type", class: "bg-blue-600 px-3 py-3 text-base text-white rounded-md hover:bg-blue-700 hover:border-blue-700 border-transparent border-solid cursor-pointer" %>
      </div>
    </div>
  <% end %>
</div>

app/views/highlight_types/edit.html.erb
<div class="text-md text-left mb-6"><%= link_to "Home", root_path, class: "text-blue-600 hover:underline" %> &#187; <%= link_to "Customers", customers_path, class: "text-blue-600 hover:underline" %> &#187; <%= link_to @customer.name, edit_customer_path(@customer), class: "text-blue-600 hover:underline" %> &#187; HighlightType "<%= @highlight_type.name %>"</div>
<div class="text-2xl text-left mb-6">Edit HighlightType</div>
<%= render "form", highlight_type: @highlight_type %>
<br>
<div>
  <%= link_to 'Delete Highlight Type', customer_highlight_type_path(@customer, @highlight_type), data: { "turbo-method": :delete }, class: "bg-red-600 px-3 py-3 text-base text-white rounded-md hover:bg-red-700 hover:border-red-700 border-transparent border-solid cursor-pointer inline-block" %>
</div>

app/views/highlight_types/new.html.erb
<h1>New highlight_type</h1>
<%= render "form", highlight_type: @highlight_type %>
<br>
<div>
  <%= link_to "Back to customer", edit_customer_path(@customer) %>
</div>

app/views/highlights/new.html.erb
<h1>New highlight</h1>

<%= render "form", highlight: @highlight %>

<br>

<div>
  <%= link_to "Back to customer", edit_customer_path(@customer) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sortable</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <div class="container mx-auto p-4 border-2">
      <%# <%= render "layouts/navbar" %>
      <%# <%= render "layouts/flash" %>
      <% flash.each do |type, msg| %>
        <div class="py-2 px-4 bg-amber-100">
          <%= msg %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>